# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModernSpectro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(1368, 701)
        Form.setStyleSheet("QWidget{\n"
"    background-color:#060226;\n"
"}")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1381, 701))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1379, 699))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.UpperSection = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.UpperSection.setGeometry(QtCore.QRect(0, 0, 1368, 80))
        self.UpperSection.setStyleSheet("QFrame {\n"
"    background-color: rgba(30, 30, 47, 204);\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"    padding: 10px;\n"
"    border:0.5px solid #170c66;\n"
"}\n"
"\n"
"\n"
"QFrame#lineTop {\n"
"    border-bottom: 1px solid rgba(255, 255, 255, 0.05);\n"
"}\n"
"")
        self.UpperSection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UpperSection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UpperSection.setObjectName("UpperSection")
        self.settingBtn = QtWidgets.QPushButton(self.UpperSection)
        self.settingBtn.setGeometry(QtCore.QRect(870, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.settingBtn.setFont(font)
        self.settingBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingBtn.setStyleSheet("QPushButton {\n"
"    background-color: #2a2a40;\n"
"    color: white;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3c3c5c;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingBtn.setIcon(icon)
        self.settingBtn.setIconSize(QtCore.QSize(25, 25))
        self.settingBtn.setObjectName("settingBtn")
        self.reportBtn = QtWidgets.QPushButton(self.UpperSection)
        self.reportBtn.setGeometry(QtCore.QRect(1040, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.reportBtn.setFont(font)
        self.reportBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reportBtn.setStyleSheet("QPushButton {\n"
"    background-color: #2a2a40;\n"
"    color: white;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3c3c5c;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/seo-report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportBtn.setIcon(icon1)
        self.reportBtn.setIconSize(QtCore.QSize(25, 25))
        self.reportBtn.setObjectName("reportBtn")
        self.helpBtn = QtWidgets.QPushButton(self.UpperSection)
        self.helpBtn.setGeometry(QtCore.QRect(1210, 20, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.helpBtn.setFont(font)
        self.helpBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.helpBtn.setStyleSheet("QPushButton {\n"
"    background-color: #2a2a40;\n"
"    color: white;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3c3c5c;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpBtn.setIcon(icon2)
        self.helpBtn.setIconSize(QtCore.QSize(25, 25))
        self.helpBtn.setObjectName("helpBtn")
        self.pushButton = QtWidgets.QPushButton(self.UpperSection)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: #00aaff;\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"    background-color:transparent;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/letter-s.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(60, 60))
        self.pushButton.setObjectName("pushButton")
        self.ConStatus = QtWidgets.QLabel(self.UpperSection)
        self.ConStatus.setGeometry(QtCore.QRect(500, 10, 251, 61))
        self.ConStatus.setStyleSheet("QLabel#connectionStatus {\n"
"    background-color: #1ab394;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 4px 10px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.ConStatus.setText("")
        self.ConStatus.setObjectName("ConStatus")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 251, 591))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 1px solid #170c66;\n"
"    margin-top: 15px;\n"
"    background-color: rgba(30, 30, 47, 204);\n"
"    border-radius:15px;\n"
"}\n"
"/*\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 5px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: rgba(30, 30, 47, 204);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 0px;\n"
"    padding:3px;\n"
"    border: 1px solid black;\n"
"}*/\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 0 0 0;\n"
"    height: 0px;\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 30, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #120e2e;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"    border:none;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/lan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comPort = QtWidgets.QComboBox(self.groupBox)
        self.comPort.setGeometry(QtCore.QRect(20, 110, 201, 41))
        self.comPort.setStyleSheet("QComboBox {\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: rgba(30, 30, 47, 204);\n"
"    border: 0.5px solid #170c66;\n"
"}")
        self.comPort.setObjectName("comPort")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 90, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color:#a6a3b8;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.baudRate = QtWidgets.QComboBox(self.groupBox)
        self.baudRate.setGeometry(QtCore.QRect(20, 180, 201, 41))
        self.baudRate.setStyleSheet("QComboBox {\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: rgba(30, 30, 47, 204);\n"
"    border: 0.5px solid #170c66;\n"
"}")
        self.baudRate.setObjectName("baudRate")
        self.badeRateLabel = QtWidgets.QLabel(self.groupBox)
        self.badeRateLabel.setGeometry(QtCore.QRect(20, 160, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.badeRateLabel.setFont(font)
        self.badeRateLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color:#a6a3b8;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.badeRateLabel.setObjectName("badeRateLabel")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 300, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #120e2e;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"    border:none;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/scatter-graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.scanMode = QtWidgets.QComboBox(self.groupBox)
        self.scanMode.setGeometry(QtCore.QRect(20, 380, 201, 41))
        self.scanMode.setStyleSheet("QComboBox {\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: rgba(30, 30, 47, 204);\n"
"    border: 0.5px solid #170c66;\n"
"}")
        self.scanMode.setObjectName("scanMode")
        self.scanModeLabel = QtWidgets.QLabel(self.groupBox)
        self.scanModeLabel.setGeometry(QtCore.QRect(20, 360, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.scanModeLabel.setFont(font)
        self.scanModeLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color:#a6a3b8;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.scanModeLabel.setObjectName("scanModeLabel")
        self.waveLengthLabel = QtWidgets.QLabel(self.groupBox)
        self.waveLengthLabel.setGeometry(QtCore.QRect(20, 510, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.waveLengthLabel.setFont(font)
        self.waveLengthLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color:#a6a3b8;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.waveLengthLabel.setObjectName("waveLengthLabel")
        self.minWaveLength = QtWidgets.QComboBox(self.groupBox)
        self.minWaveLength.setGeometry(QtCore.QRect(20, 530, 71, 41))
        self.minWaveLength.setStyleSheet("QComboBox {\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: rgba(30, 30, 47, 204);\n"
"    border: 0.5px solid #170c66;\n"
"}")
        self.minWaveLength.setObjectName("minWaveLength")
        self.maxWaveLength = QtWidgets.QComboBox(self.groupBox)
        self.maxWaveLength.setGeometry(QtCore.QRect(150, 530, 71, 41))
        self.maxWaveLength.setStyleSheet("QComboBox {\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: rgba(30, 30, 47, 204);\n"
"    border: 0.5px solid #170c66;\n"
"}")
        self.maxWaveLength.setObjectName("maxWaveLength")
        self.scanModeLabel_3 = QtWidgets.QLabel(self.groupBox)
        self.scanModeLabel_3.setGeometry(QtCore.QRect(110, 550, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.scanModeLabel_3.setFont(font)
        self.scanModeLabel_3.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color:#a6a3b8;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.scanModeLabel_3.setObjectName("scanModeLabel_3")
        self.connectBtn = QtWidgets.QPushButton(self.groupBox)
        self.connectBtn.setGeometry(QtCore.QRect(130, 240, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.connectBtn.setFont(font)
        self.connectBtn.setStyleSheet("QPushButton {\n"
"    background-color: #4c8c0b;\n"
"    color:black;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #234203;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.connectBtn.setObjectName("connectBtn")
        self.refreshBtn = QtWidgets.QPushButton(self.groupBox)
        self.refreshBtn.setGeometry(QtCore.QRect(10, 240, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.refreshBtn.setFont(font)
        self.refreshBtn.setStyleSheet("QPushButton {\n"
"    background-color: #0f2dbf;\n"
"    color:black;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #07124a;\n"
"    color:white;\n"
"}\n"
"\n"
"")
        self.refreshBtn.setObjectName("refreshBtn")
        self.plotModeLabel = QtWidgets.QLabel(self.groupBox)
        self.plotModeLabel.setGeometry(QtCore.QRect(20, 430, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.plotModeLabel.setFont(font)
        self.plotModeLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color:#a6a3b8;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.plotModeLabel.setObjectName("plotModeLabel")
        self.plotMode = QtWidgets.QComboBox(self.groupBox)
        self.plotMode.setGeometry(QtCore.QRect(20, 450, 201, 41))
        self.plotMode.setStyleSheet("QComboBox {\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: rgba(30, 30, 47, 204);\n"
"    border: 0.5px solid #170c66;\n"
"}")
        self.plotMode.setObjectName("plotMode")
        self.plotWidget = PlotWidget(self.scrollAreaWidgetContents)
        self.plotWidget.setGeometry(QtCore.QRect(310, 160, 741, 441))
        self.plotWidget.setObjectName("plotWidget")
        self.rightGrpBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.rightGrpBox.setGeometry(QtCore.QRect(1100, 80, 251, 591))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.rightGrpBox.setFont(font)
        self.rightGrpBox.setStyleSheet("QGroupBox {\n"
"    border: 1px solid #170c66;\n"
"    margin-top: 15px;\n"
"    background-color: rgba(30, 30, 47, 204);\n"
"    border-radius:15px;\n"
"}\n"
"/*\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 5px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: rgba(30, 30, 47, 204);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 0px;\n"
"    padding:3px;\n"
"    border: 1px solid black;\n"
"}*/\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 0 0 0;\n"
"    height: 0px;\n"
"}\n"
"")
        self.rightGrpBox.setObjectName("rightGrpBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.rightGrpBox)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 30, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #120e2e;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"    border:none;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon6)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.peadValue = QtWidgets.QPushButton(self.rightGrpBox)
        self.peadValue.setGeometry(QtCore.QRect(20, 90, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.peadValue.setFont(font)
        self.peadValue.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.peadValue.setStyleSheet("QPushButton {\n"
"    background-color: #2a2a40;\n"
"    color: white;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3c3c5c;\n"
"}\n"
"")
        self.peadValue.setObjectName("peadValue")
        self.centroid = QtWidgets.QPushButton(self.rightGrpBox)
        self.centroid.setGeometry(QtCore.QRect(20, 130, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.centroid.setFont(font)
        self.centroid.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centroid.setStyleSheet("QPushButton {\n"
"    background-color: #2a2a40;\n"
"    color: white;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3c3c5c;\n"
"}\n"
"")
        self.centroid.setObjectName("centroid")
        self.maxIntensity = QtWidgets.QPushButton(self.rightGrpBox)
        self.maxIntensity.setGeometry(QtCore.QRect(20, 170, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.maxIntensity.setFont(font)
        self.maxIntensity.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maxIntensity.setStyleSheet("QPushButton {\n"
"    background-color: #2a2a40;\n"
"    color: white;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3c3c5c;\n"
"}\n"
"")
        self.maxIntensity.setObjectName("maxIntensity")
        self.fwhm = QtWidgets.QPushButton(self.rightGrpBox)
        self.fwhm.setGeometry(QtCore.QRect(20, 250, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.fwhm.setFont(font)
        self.fwhm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fwhm.setStyleSheet("QPushButton {\n"
"    background-color: #2a2a40;\n"
"    color: white;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3c3c5c;\n"
"}\n"
"")
        self.fwhm.setObjectName("fwhm")
        self.snr = QtWidgets.QPushButton(self.rightGrpBox)
        self.snr.setGeometry(QtCore.QRect(20, 290, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.snr.setFont(font)
        self.snr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.snr.setStyleSheet("QPushButton {\n"
"    background-color: #2a2a40;\n"
"    color: white;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3c3c5c;\n"
"}\n"
"")
        self.snr.setObjectName("snr")
        self.auc = QtWidgets.QPushButton(self.rightGrpBox)
        self.auc.setGeometry(QtCore.QRect(20, 210, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.auc.setFont(font)
        self.auc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.auc.setStyleSheet("QPushButton {\n"
"    background-color: #2a2a40;\n"
"    color: white;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3c3c5c;\n"
"}\n"
"")
        self.auc.setObjectName("auc")
        self.pushButton_5 = QtWidgets.QPushButton(self.rightGrpBox)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 340, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #120e2e;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"    border:none;\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon7)
        self.pushButton_5.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.exportPNG = QtWidgets.QPushButton(self.rightGrpBox)
        self.exportPNG.setGeometry(QtCore.QRect(20, 390, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.exportPNG.setFont(font)
        self.exportPNG.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exportPNG.setStyleSheet("QPushButton {\n"
"    background-color: #3c81d6;\n"
"    color: black;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0d1f36;\n"
"    color: white;\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/png-file-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportPNG.setIcon(icon8)
        self.exportPNG.setIconSize(QtCore.QSize(25, 25))
        self.exportPNG.setObjectName("exportPNG")
        self.exportCSV = QtWidgets.QPushButton(self.rightGrpBox)
        self.exportCSV.setGeometry(QtCore.QRect(20, 440, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.exportCSV.setFont(font)
        self.exportCSV.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exportCSV.setStyleSheet("QPushButton {\n"
"    background-color: #0ea12c;\n"
"    color: black;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #064220;\n"
"    color: white;\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/csv-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportCSV.setIcon(icon9)
        self.exportCSV.setIconSize(QtCore.QSize(25, 25))
        self.exportCSV.setObjectName("exportCSV")
        self.exportSS = QtWidgets.QPushButton(self.rightGrpBox)
        self.exportSS.setGeometry(QtCore.QRect(20, 490, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.exportSS.setFont(font)
        self.exportSS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exportSS.setStyleSheet("QPushButton {\n"
"    background-color: #15d6a6;\n"
"    color: black;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #094536;\n"
"    color:white;\n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/display.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportSS.setIcon(icon10)
        self.exportSS.setIconSize(QtCore.QSize(25, 25))
        self.exportSS.setObjectName("exportSS")
        self.exportFullReport = QtWidgets.QPushButton(self.rightGrpBox)
        self.exportFullReport.setGeometry(QtCore.QRect(20, 540, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.exportFullReport.setFont(font)
        self.exportFullReport.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exportFullReport.setStyleSheet("QPushButton {\n"
"    background-color: #8e12cc;\n"
"    color: black;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #34074a;\n"
"    color:white;\n"
"}\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/data-analysis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportFullReport.setIcon(icon11)
        self.exportFullReport.setIconSize(QtCore.QSize(25, 25))
        self.exportFullReport.setObjectName("exportFullReport")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setGeometry(QtCore.QRect(290, 80, 781, 591))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    border: 1px solid #170c66;\n"
"    margin-top: 15px;\n"
"    background-color: rgba(30, 30, 47, 204);\n"
"    border-radius:15px;\n"
"}\n"
"/*\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 5px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: rgba(30, 30, 47, 204);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 0px;\n"
"    padding:3px;\n"
"    border: 1px solid black;\n"
"}*/\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 0 0 0;\n"
"    height: 0px;\n"
"}\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.startScanBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.startScanBtn.setGeometry(QtCore.QRect(80, 530, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.startScanBtn.setFont(font)
        self.startScanBtn.setStyleSheet("QPushButton {\n"
"    background-color: #0d7d0b;\n"
"    color: black;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #154a09;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/rocket.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startScanBtn.setIcon(icon12)
        self.startScanBtn.setIconSize(QtCore.QSize(25, 25))
        self.startScanBtn.setObjectName("startScanBtn")
        self.stopScanBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.stopScanBtn.setGeometry(QtCore.QRect(230, 530, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.stopScanBtn.setFont(font)
        self.stopScanBtn.setStyleSheet("QPushButton {\n"
"    background-color:#e01414;\n"
"    color: black;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #360909;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/stop-watch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopScanBtn.setIcon(icon13)
        self.stopScanBtn.setIconSize(QtCore.QSize(25, 25))
        self.stopScanBtn.setObjectName("stopScanBtn")
        self.clearGrpBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.clearGrpBtn.setGeometry(QtCore.QRect(390, 530, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.clearGrpBtn.setFont(font)
        self.clearGrpBtn.setStyleSheet("QPushButton {\n"
"    background-color: #8c790b;\n"
"    color: black;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #373804;\n"
"    color:white;\n"
"}\n"
"\n"
"")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearGrpBtn.setIcon(icon14)
        self.clearGrpBtn.setIconSize(QtCore.QSize(25, 25))
        self.clearGrpBtn.setObjectName("clearGrpBtn")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(250, 30, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:#bfc3d6;\n"
"}")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.zoomBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.zoomBtn.setGeometry(QtCore.QRect(550, 530, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.zoomBtn.setFont(font)
        self.zoomBtn.setStyleSheet("QPushButton {\n"
"    background-color: #945c5c;\n"
"    color: black;\n"
"    border: 1px solid #3c3c5c;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #361d1d;\n"
"    color:white;\n"
"}\n"
"\n"
"")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../../Modern GUI/Icons/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomBtn.setIcon(icon15)
        self.zoomBtn.setIconSize(QtCore.QSize(25, 25))
        self.zoomBtn.setObjectName("zoomBtn")
        self.groupBox_3.raise_()
        self.UpperSection.raise_()
        self.groupBox.raise_()
        self.plotWidget.raise_()
        self.rightGrpBox.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Spectrophotometer"))
        self.settingBtn.setText(_translate("Form", "Settings"))
        self.reportBtn.setText(_translate("Form", "Reports"))
        self.helpBtn.setText(_translate("Form", "Help ?"))
        self.pushButton.setText(_translate("Form", "SpectroPro Ultra"))
        self.pushButton_2.setText(_translate("Form", "Connections"))
        self.label.setText(_translate("Form", "COM Port"))
        self.badeRateLabel.setText(_translate("Form", "BAUD Rate"))
        self.pushButton_4.setText(_translate("Form", "Acquisition"))
        self.scanModeLabel.setText(_translate("Form", "Scan Mode"))
        self.waveLengthLabel.setText(_translate("Form", "Wave Length Range"))
        self.scanModeLabel_3.setText(_translate("Form", "to"))
        self.connectBtn.setText(_translate("Form", "Connect"))
        self.refreshBtn.setText(_translate("Form", "Refresh"))
        self.plotModeLabel.setText(_translate("Form", "Plotting Mode"))
        self.pushButton_3.setText(_translate("Form", "Live Matrics"))
        self.peadValue.setText(_translate("Form", "Peak Value"))
        self.centroid.setText(_translate("Form", "Centroid"))
        self.maxIntensity.setText(_translate("Form", "Max Intensity"))
        self.fwhm.setText(_translate("Form", "FWHM"))
        self.snr.setText(_translate("Form", "SNR"))
        self.auc.setText(_translate("Form", "AUC"))
        self.pushButton_5.setText(_translate("Form", "Exports"))
        self.exportPNG.setText(_translate("Form", "Export PNG"))
        self.exportCSV.setText(_translate("Form", "Export CSV"))
        self.exportSS.setText(_translate("Form", "Export Screenshot"))
        self.exportFullReport.setText(_translate("Form", "Export full report"))
        self.startScanBtn.setText(_translate("Form", "Start Scan"))
        self.stopScanBtn.setText(_translate("Form", "Stop Scan"))
        self.clearGrpBtn.setText(_translate("Form", "Clear Graph"))
        self.label_2.setText(_translate("Form", "Live Spectrum View"))
        self.zoomBtn.setText(_translate("Form", "Zoom"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
